import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Architecture App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='header'>
           <Link href="/contact">
            <button>Let's make it</button>
           </Link>
            <h2><Link href="/">Eng-Abdulla</Link></h2>
            <nav className='nav'>
              <Link href="/about">about</Link>
              <Link href="/project">project</Link>
              <Link href="/contact">contact</Link>
            </nav>
        </div>
        {children}
        </body>
    </html>
  )
}
